### DISCUSSION TITLE
Welcome to cloudfront-invalidator-action Discussions!

### DISCUSSION THREAD

**Discussion by er5bus** [er5bus/cloudfront-invalidator-action#1] [Announcements]
🎉 Announcement: Cloudfront invalidator action is now available in our repository!

We're excited to announce the release of our new Cloudfront invalidator action for GitHub workflows! This action makes it easy to invalidate your Cloudfront distribution either by origin or alias.

To use this action in your workflow, simply add it to your workflow file and pass in the domain name as an environment variable:

``` yaml
- name: Invalidate Cloudfront Distribution
  uses: er5bus/cloudfront-invalidator-action@v1
  with:
    domain_name: ${{ env.DOMAIN_NAME }}
```
We hope this action will be helpful for your projects and we welcome any feedback or suggestions for improvement. Let us know how it works for you!
